### ISSUE TITLE
Bad rendering

### ISSUE THREAD

**Issue by jponge** [asciidoctor/atom-language-asciidoc#1]
No matter which theme I use:

![screen shot 2014-03-10 at 11 49 14](https://f.cloud.github.com/assets/25961/2372806/aaeabfc2-a841-11e3-9fcd-328cad147f83.png)

Headers are nearly white here, and most elements of the AsciiDoc syntax do not get rendered nicely (e.g., links).

This does not seems to be the case on your project screenshot... any idea?

**Comment by antonmoiseev** [comment]
There is still lack of syntax highlighting. But the originally reported issue is fixed and we don't use hardcoded colors in the stylesheet, so I'm closing it.
