### ISSUE TITLE
add heading-1 heading-2, etc.. CSS classes to span elements

### ISSUE THREAD

**Issue by nahuel** [asciidoctor/atom-language-asciidoc#10]
Now headings of all levels are enclosed in a `<span class="markup heading asciidoc">`, so they can't be distinguished. Please use `class="markup heading-1 asciidoc"` or similar.

**Comment by nicorikken** [comment]
I guess this makes sense from a styling point of view, enabling for example a more graded view. Although I'm quite new to the styling aspect, it seems that this would imply changing the heading grammar to seperate regexes, and likewise expanding the stylesheet into 6 (equal) definitions. Not complex, maybe just unnecessary.
**Any +1's on this feature?**

**Comment by mojavelinux** [comment]
Yes, that appears to be true. See

* https://github.com/atom/language-gfm/blob/v0.85.0/grammars/gfm.cson#L129-L218
* https://github.com/burodepeper/language-markdown/blob/v0.12.0/grammars/language-markdown.json#L200-L457

As you can see from the language-markdown snippet (the second one), it appears to be possible to use nested matches, which might cut down on some of the duplication.

To be consistent with the built-in gfm language, I think we should use an additional class to represent the level, such as:

```
class="markup heading heading-1 asciidoc"
```

The class seems to be mapped directly from the name. So, in the grammar file, the name would be:

```
'name': 'markup.heading.heading-1.asciidoc'
```

**Comment by mojavelinux** [comment]
It's a good idea to study the grammar files for other languages so that we have some alignment for people creating themes.

**Comment by nicorikken** [comment]
I just created a PR to solve this issue, so that more detailed styling can take place.

**Comment by nicorikken** [comment]
@ldez is working in PR #88 to make sure the rendering is consistent in custom themes.

**Comment by nicorikken** [comment]
The improvement PR has just been merged, so this feature will be supported in the next release. Therefore I close this issue.

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
@nicorikken do you have a Twitter account? I like to give credit to the work of the community on Twitter, but I'm not sure what your handle is.
