### ISSUE TITLE
[maintainers] Inventory of tags

### ISSUE THREAD

**Issue by ldez** [asciidoctor/atom-language-asciidoc#105]
## Labels

Issues or PR types:
- bug
- question
- enhancement
- duplicate
- invalid
- declined

Issues or PR categories:
- grammar
- snippets
- infrastructure
- documentation
- styling

PR status:
- ready
- WIP

**Comment by ldez** [comment]
I added: WIP and ready.

When we are working on a PR, we add `WIP` label.
When we  think is ready, we add  `ready`label.

**Comment by nicorikken** [comment]
Let's try it

**Comment by mojavelinux** [comment]
I like it! This is something I've been wanting to align across projects in Asciidoctor, or at least have some shared foundation.

Here a few more tags I like to use:

* improvement (this is used when an existing feature is made a bit better)
* infrastructure (tasks related to the project itself, like adding an AppVeyor build)

I'm not a big fan of "wontfix". To me, it can come across as unfriendly. I prefer something like "declined". That communicates that a decision was made not to do it, but we're not saying we refuse to do it (on some other grounds).

**Comment by nicorikken** [comment]
@mojavelinux What do you think about the difference between improvement and enhancement?

**Comment by ldez** [comment]
`build` becomes `infrastructure`.
`wontfix` becomes `declined`.

Same as @nicorikken I don't understand the difference between improvement and enhancement.

**Comment by mojavelinux** [comment]
To me, the difference between improvement and enhancement is one of scale. Enhancement is something that is new and noteworthy (a mention in the release notes). You might call it a feature. Improvement is something that builds on an existing feature, maybe to make it more accurate. A refinement.

**Comment by nicorikken** [comment]
Seems fine to me, good enough in practice.

**Comment by nicorikken** [comment]
Does this need some documentation? If it is desired, I can do so, otherwise I'll close this issue.

**Comment by mojavelinux** [comment]
It might be nice to add a list with a brief description of each tag to the contributing guide. GitHub doesn't provide a way to a add description to a label, unfortunately. That would be nice to have.
