### ISSUE TITLE
Snippets - Periods get in the way

### ISSUE THREAD

**Issue by adam820** [asciidoctor/atom-language-asciidoc#11]
Snippets are tending to get in the way of regular writing. When ending a sentence, it's wanting to interpret the period as the start of a literal block. When hitting enter to drop to a new line, it pops in a literal block:
![image](https://cloud.githubusercontent.com/assets/1794794/8067988/2c4df9c8-0ebf-11e5-969c-f7e81cdc4478.png)
![image](https://cloud.githubusercontent.com/assets/1794794/8068031/5ef440b2-0ebf-11e5-959b-e687cdc19c0b.png)

This can get aggravating while trying to do bulleted lists, etc:
![image](https://cloud.githubusercontent.com/assets/1794794/8068057/88a22a82-0ebf-11e5-8f1e-47c090eb0638.png)

A workaround is to either hit Esc after each period, or otherwise disable the snippets package, but that doesn't seem user-friendly to have to do in the long-run.

Would it be possible to detect only a single period as not being the prefix, or otherwise changing the prefixes to something less ambiguous? Perhaps something like 'litbl' for Literal Block, 'exbl' for Example Block, etc.

**Comment by mojavelinux** [comment]
Is there anyway to indicate that a snippet should only trigger at the start of the line? Because the only way a literal block delimiter makes any sense is if it's at the start of a line.

**Comment by mojavelinux** [comment]
Totally agreed, btw.

**Comment by adam820** [comment]
Changing the syntax to start with "bl" might help the usability, since all the options would pop into the autocomplete:

![image](https://cloud.githubusercontent.com/assets/1794794/8068772/0da1b1d6-0ec4-11e5-9933-4d16eeac2478.png)

It's also probable that you're unlikely to ever type "blqte" ambiguously.

**Comment by adam820** [comment]
I whipped a pull request if wanted that makes the above noted changes, with a few changes. It boils down to "bl" + the first three letters of the type of delimited block:

`Comment Block: // -> blcom`
`Example Block: == -> blexa`
`Listing Block: -- -> bllis`
`Literal Block: .. -> bllit`
`Passth. Block: ++ -> blpas`
`  Quote Block: __ -> blquo`
`Sidebar Block: ** -> blsid`

If you would like to head down the road of trying to fix the overall issue of the trigger happening on EOL, then reject away.

**Comment by mojavelinux** [comment]
Another possible idea is the `bl` or `blk` prefix followed by the delimiter character. For instance `blk==` for an example block. wdyt? Do you like the letters better or would the symbols be more intuitive?

**Comment by adam820** [comment]
There's pros and cons to each, I think. After playing around with both for a bit, I think the strongest point for the symbols is that it promotes the actual Asciidoc syntax. The strongest point for the words/letters is that it doesn't require stretching for symbols or using the Shift key.

I, personally, could go either way; but I probably lean more for the symbols. I've done pull requests for both, so I suppose take/close whichever you feel is the better option.

**Comment by mojavelinux** [comment]
The other thing the symbols has going for it is that, technically, the delimiters don't indicate the type of block. For instance, an admonition block uses the example block delimiters. A literal block can be a source block when annotated with `[source]`.

Asciidoctor has introduced the terminology "structural container". That refers to the delimiter variant (dots, dashes, equal signs) which may then map to a block type (literal, listing, example).

**Comment by jaredmorgs** [comment]
This has been driving me a bit batty ever since using Atom, and I couldn't work out which package was providing the snippet. It was only me looking over someone else's shoulder that led me here. 

One approach I tried was adding a space before I entered in the macro, and that did get around the issue, but it does result in incorrectly nested markup and therefore invalid AsciiDoc. Would it be possible as part of the snippets engine to implement the key combo like:
{space}==
{space}..
{space}--
and then promote the block up one tab level?

@mojavelinux if you still wanted to enforce the notion of the structural container approach, and use a trigger like 'bl' as @adam820 suggested, you could remove the symbolic definition and use a textual representation to refer to the block type. This would introduce an element of RTFM before using snippets which might not be as intuitive as a pure textual or symbolic snippets.
```
Comment Block: // -> blslash
Example Block: == -> blequal
Listing Block: -- -> bldash
Literal Block: .. -> blstop
Passth. Block: ++ -> blplus
Quote Block: __ -> bluscr
Sidebar Block: ** -> blast
```

NOTE: If I was being pedantic, those last two break the content model by not using full words to denote the trigger. Using abbreviations may become painful when you can't quite remember what the arbitrary abbreviation for a symbol was. Continued use would work around that, but the initial UX would be poor.

For my vote, I'd suggest using the `bl..`, `bl==` as the trigger combo. I think it provides the best balance between semantic meaning while still retaining ease of use.

**Comment by mojavelinux** [comment]
> For my vote, I'd suggest using the bl.., bl== as the trigger combo. I think it provides the best balance between semantic meaning while still retaining ease of use.

After sleeping on it, I'm still in favor of this approach as well.

**Comment by jaredmorgs** [comment]
Can we progress with implementation? The double-dot snippet is driving me
crazy when writing at the moment.

On Fri, Jun 19, 2015, 16:15 Dan Allen <notifications@github.com> wrote:

> For my vote, I'd suggest using the bl.., bl== as the trigger combo. I
> think it provides the best balance between semantic meaning while still
> retaining ease of use.
>
> After sleeping on it, I'm still in favor of this approach as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/atom-language-asciidoc/issues/11#issuecomment-113387134>
> .
>
-- 

Sent from Mobile.

**Comment by antonmoiseev** [comment]
Guys, it looks like you agreed on the trigger symbols, I think PR #13 can be merged. Any objections?

**Comment by neontapir** [comment]
Please, I'd really love to see this. I trigger them all the time!

**Comment by mojavelinux** [comment]
@antonmoiseev Let's go for it! I'm getting asked about this one a lot, so I'd say the community is really looking forward to it.

**Comment by Lazar95** [comment]
This is still a problem for me, and I can't find a way to disable it. I see that the PR was merged, but even with the latest version 4.13.2 on Atom 1.0.7 causes this problem. 

If I hit `return` really fast after typing a period, nothing happens, but if I want for a little while, the snippet gets inserted. Then I have to hit `ESC` which gets annoying after a while.

It's funny how this _doesn't_ happen on beginnings of lines where I'd have use of this feature.

**Comment by Lazar95** [comment]
Woah, sorry for the confusion. Package `asciidoc-preview` was getting in way. Everything works perfectly.

**Comment by mojavelinux** [comment]
@Lazar95 Are you saying that if update both plugins, all is good or that asciidoc-preview is still causing a problem? And is that the asciidoc-preview from the Asciidoctor organization?

**Comment by Lazar95** [comment]
`asciidoc-preview` was causing the problem, I had to disable it. Actually the whole time I was using only `asciidoc-preview`'s highlight syntax (I installed both add-ons at the same time and I just assumed that I was getting preview from that package and highlight from your package -- turns out your pacakge was completely overridden). Now that I disabled it, I can see that your package uses much better highlighting. And yes, the `asciidoc-preview` package is form [here](https://atom.io/packages/asciidoc-preview).

**Comment by mojavelinux** [comment]
I don't think that asciidoc-preview adds syntax highlighting. AsciiDoc support is handled by two plugins, one does the language feature the other does the preview. They shouldn't step on each other's toes.

* https://github.com/asciidoctor/atom-asciidoc-preview
* https://github.com/asciidoctor/atom-language-asciidoc

If they do, that's a problem that needs to be addressed.

**Comment by Lazar95** [comment]
Well the only thing I can say is that once I disabled `asciidoc-preview`, the highlighting became richer -- things that weren't being highlighted before were now colurful. Also the periods getting in the way problem wasn't an issue anymore. How can I help? Should I post screenshots?

**Comment by mojavelinux** [comment]
The way I'd proceed is to open the DOM inspector inside of Atom (enable the developer tools) and see which style is being applied on an element that is or is not colored depending on whether the plugin is installed. If the asciidoc-preview plugin is styling something it shouldn't be, then we've identified our problem. We expect that the asciidoc-preview doesn't affect the editor in anyway*. In other words, I think one plugin should be helping the editor and the other plugin handling the preview...and we need to ensure that we are sticking to that separation (if we all agree that's the way to go).

\* except autocomplete, which IMO should be in the language feature plugin

**Comment by nicorikken** [comment]
Since the fix has been merged, the debugging relates to `asciidoc-preview`, and the progress on this issue has stalled, I close this issue.

**Comment by mojavelinux** [comment]
We also have a new proposal for code assist in #23.
