### ISSUE TITLE
Create new list item on enter

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/atom-language-asciidoc#113]
When you're in a list, it would be helpful if a new list item was started automatically upon pressing enter (or perhaps Ctrl+enter).

This feature is implemented in the [Markdown Writer](https://github.com/zhuochun/md-writer/blob/master/lib/helpers/line-meta.coffee) package. I'm not sure if this feature belongs in this package, but I wanted to raise it so that we can find a home for it, one way or another.

**Comment by nicorikken** [comment]
Would be nice, similarly I could image similar intelligent behavior for indenting, and even marking done for todo-lists.

**Comment by ldez** [comment]
If I can disabled this feature it will be nice :wink:

**Comment by mojavelinux** [comment]
Perhaps this is a separate plugin? Or perhaps we should have "AsciiDoc Writer" where we can put this and the image helper.

**Comment by ldez** [comment]
@mojavelinux It's a very good idea !

**Comment by ldez** [comment]
Reported to https://github.com/asciidoctor/atom-asciidoc-assistant/issues/9
