### ISSUE TITLE
AsciiDoc URL syntax

### ISSUE THREAD

**Issue by ldez** [asciidoctor/atom-language-asciidoc#123]
Is it valid syntaxes for url ?

```adoc
mailto:doc.writer@example.com
```
and

```adoc
Go on link:foobar now
```

**Comment by mojavelinux** [comment]
No, the square brackets are required. These are inline macros, so they must have the form `<name>:<target>[<attrlist>]`.

**Comment by ldez** [comment]
Thanks, I will fix this in #122

**Comment by mojavelinux** [comment]
:+1:
