### ISSUE TITLE
Migrate autocompletion to the grammar package.

### ISSUE THREAD

**Issue by ldez** [asciidoctor/atom-language-asciidoc#133]
Migrate autocompletion to the grammar package.

**Comment by nicorikken** [comment]
The roadmap I envision:

1. **language-asciidoc** copy autocompletion over and release
2. **language-asciidoc** copy outstanding autocompletion issues over
3. **asciidoc-preview** remove autocompletion support and release
4. **language-asciidoc** convert to new autocompletion API version
5. **language-asciidoc** address currently outstanding autocompletion issues (like scope)

**Comment by ldez** [comment]
and merge https://github.com/asciidoctor/atom-asciidoc-preview/pull/138

**Comment by ldez** [comment]
- [x] `language-asciidoc` copy autocompletion over and release
- [ ] `language-asciidoc` release
- [x] `asciidoc-preview` remove autocompletion support
- [ ] `asciidoc-preview` release
- [x] `language-asciidoc` address currently outstanding autocompletion issues (like scope)
- [x] `language-asciidoc` convert to new autocompletion API version

> `language-asciidoc` copy outstanding autocompletion issues over

Not needed I have already fixed all issues :wink:

Waiting for the `asciidoc-preview` release :smile_cat:

**Comment by ldez** [comment]
- [x] `asciidoc-preview` release
- [x] create a new package`autocomplete-asciidoc` and release

All it's done now! :tada:

**Comment by mojavelinux** [comment]
Amazing work!

**Comment by nicorikken** [comment]
In hindsight I'm glad we moved the autocomplete off to a separate package. Nice work.
