### ISSUE TITLE
Request for Table formatting/normalization

### ISSUE THREAD

**Issue by sengopal** [asciidoctor/atom-language-asciidoc#140]
## Description
**Enhancement Request**

Apologies if this is not the correct repo for this request. Can we get table data formatting and normalization helping both authoring and readability of the adoc file. 
**Reference**: Previously used this for markdown http://markdowntable.com/ and seems there is one for atom as well - https://atom.io/packages/markdown-table-formatter

## Screenshots
N/A

## Syntax example
N/A

**Comment by ldez** [comment]
Thanks to your contribution.

The AsciiDoctor tables are more rich than Markdown tables, multiple syntax are possible, provide a formatting seems to me complex.

The grammar package provide the highlighting of text only.

We are currently thinking to an AsciiDoctor assitant/writer package.

Due to this I must decline your request, sorry.

**Comment by mojavelinux** [comment]
I agree this would work best as a separate package (maybe included down the line in the assistance package). However, I think it would be pretty tough to implement without messing up the table. It could work for simple tables, but for complex tables, it would almost have to do AsciiDoc to AsciiDoc conversion.

**Comment by nicorikken** [comment]
Then again, the Asciidoctor syntax includes attributes defining how a properly aligned table should look. Like multi span columns, text alignment. Would certainly be great, but indeed complex.

**Comment by sengopal** [comment]
Sure. Just thought it would be good addition. I was actually looking for something which formats the spacing of the columns evenly. However, it is complex with the column span and other formatting attributes. 

Anyway thanks for replying 👍
