### ISSUE TITLE
Show attribute value when mouse is overed over attribute reference

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/atom-language-asciidoc#141]
## Description

It would be really cool if the value of the attribute appeared when you hover the mouse over an attribute reference. This would allow you to verify that the value is correct without having to scroll all the way to the top of the document where it is defined.

## Screenshots

![hover-resolve-attribute](https://cloud.githubusercontent.com/assets/79351/15496668/d103897c-2153-11e6-8bd3-05e32bb85425.png)

I'm not sure if this feature belongs in this package or perhaps it belongs in the autocomplete package.

**Comment by ldez** [comment]
Move to https://github.com/asciidoctor/atom-asciidoc-assistant/issues/8
