### ISSUE TITLE
Inline strong not higlhighted in table

### ISSUE THREAD

**Issue by nicorikken** [asciidoctor/atom-language-asciidoc#142]
Inline strong content is valid, but not properly recognized.

```
|===
|*TBD*|*TBD*
|SN:  |SN:
|VC:  |VC:
|MAC: |MAC:
|===
```

![screen shot 2016-05-24 at 14 45 48](https://cloud.githubusercontent.com/assets/7458098/15504374/eea76d84-21be-11e6-9c56-3db75e50000a.png)

Scopes at Cursor (first strong, not recognized)

- source.asciidoc
- markup.table.asciidoc
- markup.table.content.asciidoc
- markup.meta.attribute-list.asciidoc

Scopes at Cursor (right strong, recognized)

- source.asciidoc
- markup.table.asciidoc
- markup.table.content.asciidoc
- markup.strong.constrained.asciidoc
- markup.bold.asciidoc

Also confirmed for emphasis. So the issue at hand here, is that inline between two pipes is not properly higlighted.

A similar edge-case
<img width="112" alt="screen shot 2016-05-24 at 14 54 11" src="https://cloud.githubusercontent.com/assets/7458098/15504467/7230ec2a-21bf-11e6-9b66-bf77c11303a4.png">
Which renders like:
<img width="676" alt="screen shot 2016-05-24 at 14 55 04" src="https://cloud.githubusercontent.com/assets/7458098/15504483/8b961488-21bf-11e6-9a7b-de372af5f3ca.png">

**Comment by ldez** [comment]
you must have a space between columns.

**Comment by nicorikken** [comment]
Right, trailing space is suggested in the manual, but not clearly stated. The preview happily accepts it. I can agree leaving this be, as this can at least be considered bad practice.
