### ISSUE TITLE
Source block delimiter with .... (literal)

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/atom-language-asciidoc#146]
## Description

Source block literal with `....` literal prevents the rest of the document from being correctly highlighted.

## Screenshots

![source-block](https://cloud.githubusercontent.com/assets/333276/15590261/1bb502a8-2397-11e6-8144-ed1ea6c6dbed.png)

## Syntax example

```adoc
= Source block delimiter ....

== Exemple

[source,adoc]
....
:uri-homepage: http://asciidoctor.org // <1>
:uri-docs: {uri-homepage}/docs // <2>

 - {uri-docs}/user-manual
 - {uri-docs}/asciidoc-syntax-quick-reference
....
// <1> URL de base du site Asciidoctor
// <2> Réutilise la variable définie juste au dessus pour ajouter `/docs`

== Résultat

:uri-homepage: http://asciidoctor.org
:uri-docs: {uri-homepage}/docs

 - {uri-docs}/user-manual
 - {uri-docs}/asciidoc-syntax-quick-reference

---
```

**Comment by ldez** [comment]
I will fix this quickly...

**Comment by ldez** [comment]
but it's a real case?
use `source` and literal delimiter ?

**Comment by Mogztter** [comment]
@ldez @mojavelinux Good question, I don't know if there's another way to write this.
A better exemple is:

```adoc
= Source block delimiter ....

== Exemple

[source]
....
:testdir: ${project.build.testSourceDirectory} // <1>
:testpkg: {testdir}/org/asciidoctor // <2>

[source,java]
----
include::{testpkg}/WhenAttributesAreUsed.java[tag=uri-scheme] // <3>
----
<1> Positionne l'attribut permettant de masquer le schéma sur les liens
....

// <1> Utilise une variable du build Maven (filtering)
// <2> Réutilise la variable définie juste au dessus pour ajouter le package
// <3> Précise le tag à utiliser (possibilité de préciser plusieurs tag séparé par des virgules)

== Résultat

:testpkg: src/test/java/org/asciidoctor

[source,java,indent=0]
----
include::{testpkg}/WhenAttributesAreUsed.java[tags=uri-scheme]
----
<1> Positionne l'attribut permettant de masquer le schéma sur les liens
```

![source-block-rendered2](https://cloud.githubusercontent.com/assets/333276/15590677/1fcf3550-2399-11e6-9b5c-ddc603cfb18f.png)

**Comment by ldez** [comment]
The documentation talk about open block and listing bloc but literal...

Cool, a sample :+1:

**Comment by ldez** [comment]
You can do that with open block:

```adoc
= Source block delimiter ....

== Exemple

[source]
--
:testdir: ${project.build.testSourceDirectory} // <1>
:testpkg: {testdir}/org/asciidoctor // <2>

[source,java]
----
include::{testpkg}/WhenAttributesAreUsed.java[tag=uri-scheme] // <3>
----
<1> Positionne l'attribut permettant de masquer le schéma sur les liens
--

// <1> Utilise une variable du build Maven (filtering)
// <2> Réutilise la variable définie juste au dessus pour ajouter le package
// <3> Précise le tag à utiliser (possibilité de préciser plusieurs tag séparé par des virgules)

== Résultat

:testpkg: src/test/java/org/asciidoctor

[source,java,indent=0]
----
include::{testpkg}/WhenAttributesAreUsed.java[tags=uri-scheme]
----
<1> Positionne l'attribut permettant de masquer le schéma sur les liens

```

**Comment by mojavelinux** [comment]
Yep, it's valid. The source style can be on listing, literal or open
structural containers.

**Comment by ldez** [comment]
But it's explained nowhere else. :cry: 

Same thing for other styles, like passthrough, admonition or quotes ??

**Comment by mojavelinux** [comment]
> But it's explained nowhere else. :cry:

:sob: 

The official ruling is that the source style can be applied to a verbatim structural container, of which there are two: listing (hyphens) and literal (dots). The open block was an experiment. I've since concluded that using open block for this purpose is not a good practice and we shouldn't support it in the grammar.

**Comment by ldez** [comment]
Another question, in the documentation it's write that Open block doesn't act passthrough blocks.

> Open block: Anonymous block that can act as any block except passthrough or table blocks.
  
http://asciidoctor.org/docs/user-manual/#built-in-blocks-summary

If I do:
```adoc
[pass]
--
<div>
  <u>underline me</u>
</div>
--
foo
```

the render:

![capture du 2016-05-27 09-55-51](https://cloud.githubusercontent.com/assets/5674651/15601721/3ff16f9e-23f1-11e6-9061-7b4d245ac762.png)

I have misunderstood something?

**Comment by ldez** [comment]
@Mogztter you can prevent callout substitution for a better rendering. 

```adoc
[source]
....
:testdir: ${project.build.testSourceDirectory} // \<1>
:testpkg: {testdir}/org/asciidoctor // <2>
....
```

![capture du 2016-05-27 13-15-37](https://cloud.githubusercontent.com/assets/5674651/15606524/2575efca-240d-11e6-9929-1b4687c26373.png)

**Comment by lucascosti** [comment]
I'm not sure if this is the same issue as this, but I am also experiencing an open block breaking highlighting.

![asciidoc-language-bug](https://cloud.githubusercontent.com/assets/4434330/15641804/9e89b024-2686-11e6-9c49-bf5fc694b746.png)

This is with language-asciidoc v. 1.4.6

**Comment by ldez** [comment]
@lucascosti can you open another issue?
Your problem is different.
In this new issue, can you provide a syntax sample?
Thanks.

**Comment by lucascosti** [comment]
@ldez yep, sure; done as #148 .

**Comment by mojavelinux** [comment]
>  in the documentation it's write that Open block doesn't act passthrough blocks.

It can. Here's the definitive list atm: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L275

We're still struggling a bit to decide what open block should be allowed to do, and when to use it. My current position is that an open block should be allowed "masquerade" as other complex blocks (example, sidebar, etc), but most of the time it is used simply to group blocks together with no meaning (an anonymous group so to speak) or for extensions. (I'm not a big fan of using open blocks for verbatim content).
