### ISSUE TITLE
Add examples support

### ISSUE THREAD

**Issue by neontapir** [asciidoctor/atom-language-asciidoc#15]
I'd like to see support for examples, such as this one:

    .An example
    ===========
    This is an example example. 
    ===========

For sidebars and examples, I think having a different color background would make the most sense. Since the default style puts examples in a yellow sidebar, it would be nice if the editor followed suit I'm not sure how to best achieve that in a style-agnostic way, however.

I'm having trouble getting any of the Asciidoc package tests to run, so I'm not able to make much progress on this myself.

**Comment by neontapir** [comment]
I've figured out how to match the example block, but I don't know how to change its formatting. I have been using the comment block as an analogy, and I don't see anything in the LESS file to handle comment blocks either. Is there more to the plugin than what's checked into Github?

**Comment by antonmoiseev** [comment]
The `name` property becomes the matched element's CSS. For example, when you match italic:
```cson
{
  'match': '(?<=^|\\s)(_[^_]+_)'
  'captures':
    '0': 'name': 'markup.italic.asciidoc'
}
```
...the matched element is wrapped into a span and three CSS classes assigned to it:
```html
Paragraph with <span class="markup italic asciidoc">_italic_</span> text.
```

JFYI, blocks is something that I would love to refactor first. There are lots of them, many of them inherit common properties, but right now we have to add a separate rule for each of them which leads to grammar file complexity and code duplication.

**Comment by neontapir** [comment]
I got the example block to work (my dev package wasn't loaded). I'll take a crack at abstracting block elements while I'm at it.

**Comment by mojavelinux** [comment]
:+1:

**Comment by neontapir** [comment]
I went a little bonzo. Would you prefer an omnibus pull request with support for other elements as well, or would you like me to submit the example section support as a separate request?

**Comment by antonmoiseev** [comment]
I personally don't mind reviewing multiple elements at once, if the overall size of the changes is manageable for review and there are tests for new elements :wink:

**Comment by neontapir** [comment]
In that case, I submitted the pull request last night. :)

**Comment by mojavelinux** [comment]
:+1:

**Comment by nicorikken** [comment]
After an extensive back and forth in PR #17 this issue was fixed. Thanks @neontapir and @antonmoiseev

**Comment by mojavelinux** [comment]
:+1:
