### ISSUE TITLE
Don't uniformly colorize content of open block

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/atom-language-asciidoc#154]
## Description

The open block is often used to group other block-level AsciiDoc content. (It's most frequently used to attach arbitrary block-level content to a list item). As such, the content of the open block should be highlighted as AsciiDoc. Currently, the content of an open block is uniformly colorized (like a literal block) and there is no indication of syntax inside its boundaries. We can still highlight the delimiters (aka fences).

## Screenshots

![open-block](https://cloud.githubusercontent.com/assets/79351/15882197/a47800f2-2cf9-11e6-9e6c-dae1bf693817.png)

## Syntax example

```adoc
Using Bundler::
+
--
Add the `jekyll-asciidoc` plugin gem to your [path]_Gemfile_:

[source,ruby]
----
group :jekyll_plugins do
  gem 'jekyll-asciidoc'
end
----

Then, run the Bundler command to install it:

 $ bundle install
--
```

**Comment by ldez** [comment]
It's not colorized like a literal block but like a raw code block.

**Comment by ldez** [comment]
Solution A:
![capture du 2016-06-08 08-01-53](https://cloud.githubusercontent.com/assets/5674651/15884246/5a0fc01c-2d4f-11e6-823d-f8500b14fb30.png)

Solution B:
![capture du 2016-06-08 08-02-14](https://cloud.githubusercontent.com/assets/5674651/15884247/5a36f150-2d4f-11e6-8f87-4b4c3c0fd029.png)

@mojavelinux What do you prefer?

**Comment by mojavelinux** [comment]
> It's not colorized like a literal block but like a raw code block.

Yes, that's what I meant.

I like solution A. The reason I say that is that an open block is merely a grouping block (like a div, really). So we should only put a lasso around it rather than imply that it is some sort of semantic type via color.

**Comment by ldez** [comment]
Now, I better understand the meaning of this block
