### ISSUE TITLE
Highlight block-level AsciiDoc inside example and sidebar blocks

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/atom-language-asciidoc#157]
## Description

The example and sidebar blocks are compound blocks, which means they support nested AsciiDoc content. Therefore, the language should descend into the block to match and highlight AsciiDoc syntax.

## Screenshots

In this screenshot, the block title and the literal block should be highlighted. It's good that the image block is highlighted, but the highlighting shouldn't be limited to just block macros.

![example-block-screenshot](https://cloud.githubusercontent.com/assets/79351/15912665/ef293f28-2d92-11e6-9661-34039e88b6f0.png)

## Syntax example

```adoc
====
Example block text.

.This is a screenshot
image::screenshot.jpg[]

....
literal block
....
====
```

**Comment by mojavelinux** [comment]
We probably should do the same for quote blocks as well, though it's much less likely that a quote block contains nested AsciiDoc blocks.

**Comment by ldez** [comment]
Now with #158:

![capture du 2016-06-09 21-16-42](https://cloud.githubusercontent.com/assets/5674651/15943094/a5b95fb2-2e87-11e6-8473-7284f1df6ad9.png)
![capture du 2016-06-09 21-17-18](https://cloud.githubusercontent.com/assets/5674651/15943095/a5e30376-2e87-11e6-84ed-bdafe3280f19.png)
