### ISSUE TITLE
Feature Request: commands for bolding, italicizing and performing other common markup actions in asciidoc

### ISSUE THREAD

**Issue by fusion809** [asciidoctor/atom-language-asciidoc#159]
Hi,

I would like to request that Atom commands (with corresponding keyboard shortcuts) be added to bold, italicize, add code-blocks to, *etc.* selected markup. Although, I realize that these features may be best added to a separate package like the Asciidoc equivalent to the [`markdown-writer`](https://github.com/zhuochun/md-writer) package. 

Thanks for your time,
Brenton

**Comment by nicorikken** [comment]
@fusion809 Am I correct in understanding that such a feature already exists in the `markdown-writer` package? The Atom Asciidoctor project has been split up into several different packages as well, but certainly this seems to be a worthy feature.

**Comment by fusion809** [comment]
The `markdown-writer` package provides all these features and more for `markdown`. I'm basically just suggesting that an asciidoc equivalent to that package be built. I'm writing my first Jekyll post in Asciidoc (after writing ~ 10-20 in Markdown) using Atom and the features of `markdown-writer` are definitely ones I'm missing.

**Comment by ldez** [comment]
Please move your issue here : https://github.com/asciidoctor/atom-asciidoc-assistant
