### ISSUE TITLE
Unable to run package tests due to null objects

### ISSUE THREAD

**Issue by neontapir** [asciidoctor/atom-language-asciidoc#16]
When I try to run the Coffee script tests included with this package using `Application:Run All Specs`, I get null object errors for 9/9 tests. The first error is:

    AsciiDoc grammar
      it parses the grammar
        TypeError: Cannot read property 'grammarForScopeName' of undefined
        TypeError: Cannot read property 'grammarForScopeName' of undefined
        at asciidoc-spec.coffee:9:28
        TypeError: Cannot read property 'scopeName' of null
        TypeError: Cannot read property 'scopeName' of null
        at asciidoc-spec.coffee:13:19

When I include this test spec in the file, it does not throw an error:
    
    describe "when a test is written", ->
      fit "has some expectations that should pass", ->
        expect("apples").toEqual("apples")
        expect("oranges").not.toEqual("apples")

When I run `Window: Run Package Specs`, no results window is launched and nothing seems to happen.

Is there some special way that I need to call these tests to include the Asciidoctor package?

**Comment by antonmoiseev** [comment]
What version of Atom and language-asciidoc you use? I assume it's 1.0.0 and 0.11.1 respectively. Tests pass without any errors for me. I run the tests this way:

1. Clone git repo locally
2. Open the dir in the command-line.
3. `apm link --dev`
3. `apm test`

**Comment by neontapir** [comment]
That solved my issue, I was able to run the tests using the above steps. Thanks!
