### ISSUE TITLE
Getting error with Stylesheet

### ISSUE THREAD

**Issue by thesteve0** [asciidoctor/atom-language-asciidoc#160]
## Description

No matter what editor stylesheet I use I get an error with line 4 in the stylesheet for this. I get a complaint that
line 4 @syntax-color-constant is not found. If I change that to a constant, like white, then it throws an error on the next @ in the statement. 

https://github.com/asciidoctor/atom-language-asciidoc/blob/master/styles/asciidoc.atom-text-editor.less#L4

I am on Fedora 23 with atom 0.186.0

**Comment by ldez** [comment]
`@syntax-color-constant` is provided by the themes, but some themes does not provide this value.

Which theme do you use ?

**Comment by ldez** [comment]
this works:

```less
@syntax-text-mark: mix(white, @syntax-color-keyword, 50%);
```

**Comment by ldez** [comment]
You are using a very old Atom (0.186.0), the current version is 1.8.0.
The package is only supported by Atom after 1.0.0.

**Comment by thesteve0** [comment]
Thanks so much - I am all good now.
