### ISSUE TITLE
Listing block breaks highlighting

### ISSUE THREAD

**Issue by lucascosti** [asciidoctor/atom-language-asciidoc#161]
## Description

A `[listing]` block ([as per the user manual](http://asciidoctor.org/docs/user-manual/#built-in-blocks-summary)) breaks the highlighting.
## Screenshots

![listingblockproblem](https://cloud.githubusercontent.com/assets/4434330/17235977/b7eba780-5588-11e6-8199-10717992c3f1.png)
## Syntax example

``` adoc
== Heading

This para is highlighted normally.

[listing]
----
This is a listing.
----

Everything after here has broken highlighting.
```

**Comment by ldez** [comment]
See #158 and http://asciidoctor.org/docs/user-manual/#listing-blocks.
