### ISSUE TITLE
Deprecations in language-asciidoc/styles/asciidoc.atom-text-editor.less

### ISSUE THREAD

**Issue by rumpelsepp** [asciidoctor/atom-language-asciidoc#170]
I hope I have inserted the new lines correctly; the link, generated by the deprecation cop in atom, is too long to be usable on github. So I copy-pasted this manually.

Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* atom-text-editor::shadow .asciidoc .markup.bold, :host .asciidoc .markup.bold => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--bold,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--bold

* atom-text-editor::shadow .asciidoc .markup.italic, :host .asciidoc .markup.italic => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--italic,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--italic

* atom-text-editor::shadow .asciidoc .markup.mark, :host .asciidoc .markup.mark => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--mark,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--mark

* atom-text-editor::shadow .asciidoc .markup.highlight, :host .asciidoc .markup.highlight => atom-text-editor.editor .syntax--asciidoc .syntax--markup.highlight,atom-text-editor .syntax--asciidoc .syntax--markup.highlight

* atom-text-editor::shadow .asciidoc .markup.character-reference, :host .asciidoc .markup.character-reference => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--character-reference,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--character-reference

* atom-text-editor::shadow .asciidoc .markup.biblioref, :host .asciidoc .markup.biblioref, atom-text-editor::shadow .asciidoc .markup.blockid, :host .asciidoc .markup.blockid => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--biblioref,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--biblioref, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--blockid,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--blockid

* atom-text-editor::shadow .asciidoc .markup.xref, :host .asciidoc .markup.xref => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--xref,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--xref

* atom-text-editor::shadow .asciidoc .markup.admonition, :host .asciidoc .markup.admonition, atom-text-editor::shadow .asciidoc .markup.heading, :host .asciidoc .markup.heading, atom-text-editor::shadow .asciidoc .markup.heading-0, :host .asciidoc .markup.heading-0, atom-text-editor::shadow .asciidoc .markup.heading-1, :host .asciidoc .markup.heading-1, atom-text-editor::shadow .asciidoc .markup.heading-2, :host .asciidoc .markup.heading-2, atom-text-editor::shadow .asciidoc .markup.heading-3, :host .asciidoc .markup.heading-3, atom-text-editor::shadow .asciidoc .markup.heading-4, :host .asciidoc .markup.heading-4, atom-text-editor::shadow .asciidoc .markup.heading-5, :host .asciidoc .markup.heading-5 => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--admonition,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--admonition, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--heading,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--heading, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--heading-0,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--heading-0, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--heading-1,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--heading-1, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--heading-2,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--heading-2, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--heading-3,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--heading-3, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--heading-4,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--heading-4, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--heading-5,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--heading-5

* atom-text-editor::shadow .asciidoc .markup.meta.attribute-list, :host .asciidoc .markup.meta.attribute-list, atom-text-editor::shadow .asciidoc .markup.substitution, :host .asciidoc .markup.substitution => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--meta.syntax--attribute-list,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--meta.syntax--attribute-list, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--substitution,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--substitution

* atom-text-editor::shadow .asciidoc .markup.heading.blocktitle, :host .asciidoc .markup.heading.blocktitle => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--heading.syntax--blocktitle,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--heading.syntax--blocktitle

* atom-text-editor::shadow .asciidoc .markup.todo.box, :host .asciidoc .markup.todo.box, atom-text-editor::shadow .asciidoc .markup.list.bullet, :host .asciidoc .markup.list.bullet => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--todo.syntax--box,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--todo.syntax--box, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--list.syntax--bullet,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--list.syntax--bullet

* atom-text-editor::shadow .asciidoc .markup.macro.block, :host .asciidoc .markup.macro.block => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--macro.syntax--block,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--macro.syntax--block

* atom-text-editor::shadow .asciidoc .markup.super, :host .asciidoc .markup.super => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--super,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--super

* atom-text-editor::shadow .asciidoc .markup.sub, :host .asciidoc .markup.sub => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--sub,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--sub

* atom-text-editor::shadow .asciidoc .markup.table.cell.delimiter, :host .asciidoc .markup.table.cell.delimiter, atom-text-editor::shadow .asciidoc .markup.table.delimiter, :host .asciidoc .markup.table.delimiter => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--table.syntax--cell.syntax--delimiter,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--table.syntax--cell.syntax--delimiter, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--table.syntax--delimiter,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--table.syntax--delimiter
atom-text-editor::shadow .asciidoc .markup.table.content, :host .asciidoc .markup.table.content => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--table.syntax--content,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--table.syntax--content

* atom-text-editor::shadow .asciidoc .markup.block.sidebar, :host .asciidoc .markup.block.sidebar, atom-text-editor::shadow .asciidoc .markup.block.passthrough, :host .asciidoc .markup.block.passthrough, atom-text-editor::shadow .asciidoc .markup.block.front-matter, :host .asciidoc .markup.block.front-matter, atom-text-editor::shadow .asciidoc .markup.block.example, :host .asciidoc .markup.block.example => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--block.syntax--sidebar,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--block.syntax--sidebar, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--block.syntax--passthrough,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--block.syntax--passthrough, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--block.syntax--front-matter,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--block.syntax--front-matter, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--block.syntax--example,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--block.syntax--example

* atom-text-editor::shadow .asciidoc .markup.block.listing, :host .asciidoc .markup.block.listing, atom-text-editor::shadow .asciidoc .markup.block.literal, :host .asciidoc .markup.block.literal => atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--block.syntax--listing,atom-text-editor .syntax--* 
asciidoc .syntax--markup.syntax--block.syntax--listing, atom-text-editor.editor .syntax--asciidoc .syntax--markup.syntax--block.syntax--literal,atom-text-editor .syntax--asciidoc .syntax--markup.syntax--block.syntax--literal

* atom-text-editor::shadow .asciidoc .super, :host .asciidoc .super => atom-text-editor.editor .syntax--asciidoc .syntax--super,atom-text-editor .syntax--asciidoc .syntax--super

* atom-text-editor::shadow .asciidoc .sub, :host .asciidoc .sub => atom-text-editor.editor .syntax--asciidoc .syntax--sub,atom-text-editor .syntax--asciidoc .syntax--sub

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by ldez** [comment]
thanks for your contributions.

But currently `::shadow` is used by Atom.
And you cannot change selector (BOM style).

**Comment by ldez** [comment]
I'm stupid...

Can you make a PR please ?

**Comment by ldez** [comment]
this become my priority.
