### ISSUE TITLE
1.6.0 regressions?

### ISSUE THREAD

**Issue by lucascosti** [asciidoctor/atom-language-asciidoc#172]
## Description

With the 1.6.0 update, a lot has changed, and I'm not sure it is all intentional? Especially for the headings, titles, block options: they are all the same reddish colour now, whereas each had its own style before. Also things like attributes no longer have any styling applied to them.

I just wanted to check if this was deliberate, or a bug?

Atom 1.12.5, One Dark UI and Syntax themes, lanuage-asciidoc 1.6.0

## Screenshots

![2016-11-22](https://cloud.githubusercontent.com/assets/4434330/20510958/e2a968a8-b0bf-11e6-98da-6a85b2a6bcd5.png)

## Syntax example

```adoc
== Configuring {ProductShortName} for Microsoft Azure

.Starting {ProductShortName} as a Service at Boot on Red&nbsp;Hat&nbsp;Enterprise&nbsp;Linux

If you are starting {ProductShortName} as a service on Red&nbsp;Hat&nbsp;Enterprise&nbsp;Linux in Microsoft Azure, you must change the following configuration of the {ProductShortName} service to ensure that it starts after the Azure virtual machine host name has been initialized.

Open `/etc/systemd/system/multi-user.target.wants/eap7-standalone.service` and add a dependency on `waagent.service`:

Replace the following line:

[options="nowrap"]
----
After=syslog.target network.target
----

with:

[options="nowrap"]
----
After=syslog.target network.target waagent.service
Requires=waagent.service
----

[[lb_with_mod_cluster]]
.Load Balancing with mod_cluster
```

**Comment by mojavelinux** [comment]
I think it's safe to say that's a regression. It looks like purely a stylesheet issue. I think this is what @ldez is currently addressing in https://github.com/asciidoctor/atom-language-asciidoc/pull/171.

**Comment by ldez** [comment]
It's my bad, I revert.

**Comment by ldez** [comment]
1.6.1 come very quickly.

**Comment by lucascosti** [comment]
Thanks guys, I really appreciate all the work that you do! :)
