### ISSUE TITLE
Some Ruby source breaks syntax colouring

### ISSUE THREAD

**Issue by gquintana** [asciidoctor/atom-language-asciidoc#175]
## Description

In Ruby source block, something breaks syntax colouring.

## Screenshots

![image](https://cloud.githubusercontent.com/assets/755587/21745010/dc8aec18-d521-11e6-9d87-6f101cef6aa8.png)

## Syntax example

```adoc
#Ruby source Test

[source,ruby]
----
class Person
  def name            # <1>
    @name
  end
  def name=(new_name) # <2>
    @name=new_name
  end
end
----
<1> Declare a getter
<2> Declare a setter

Here the  syntax colouring is broken.
The single quote:  let's triggers something
```

**Comment by gquintana** [comment]
The `# <2>` in the Ruby source triggers the problem. Removing it solves the problem.

**Comment by ldez** [comment]
Thanks for reporting.

It's a problem with the Atom Ruby grammar package.

You can reproduce the bug with Markdown in Atom:

```markdown
# Ruby source Test

\`\`\`ruby
class Person
  def name            # foo
    @name
  end
  def name=(new_name)  # foo
    @name=new_name
  end
end
\`\`\`

Here the  syntax colouring is broken.
The single quote:  let's triggers something
```
I use `\` only to escape char in Github.

**Comment by ldez** [comment]
It's not a bug with Atom Langauge Asciidoc package but with Atom Ruby grammar package.
