### ISSUE TITLE
Wrong highlighting in lists when using stars

### ISSUE THREAD

**Issue by rumpelsepp** [asciidoctor/atom-language-asciidoc#18]
There are problems when using `*` in a list like:

```
* bla bla *bla*
```
![screenshot from 2015-07-10 10-29-14](https://cloud.githubusercontent.com/assets/1961699/8614892/8c046a22-26ee-11e5-8f70-762fb474093d.png)

**Comment by nicorikken** [comment]
Duplicate of issue #9 for which I just created a pull-request. Issue can be closed. @rumpelsepp you should see this feature in your editor soon!

**Comment by rumpelsepp** [comment]
Nice!
