### ISSUE TITLE
Java try with resource syntax highlighting

### ISSUE THREAD

**Issue by garyrussell** [asciidoctor/atom-language-asciidoc#190]
## Description

A code snippet with Java "try with resource" does not terminate highlighting when exiting block.

## Screenshots

![screen shot 2018-06-19 at 1 02 50 pm](https://user-images.githubusercontent.com/483832/41612493-1bdabae4-73c1-11e8-913a-3c9aefe2159b.png)

## Syntax example

```adoc
[source,java]
----
public void foo(String in) {
    try (FileInputStream is = new FileInputStream("/tmp/foo")) {
        is.read();
    }
    catch (Exception e) {
        throw new RuntimeException(e);
    }
}
----

Test foo bar.
```

**Comment by mojavelinux** [comment]
This needs to be reported here: https://github.com/atom/language-java. This language simply delegates to that language, so if that language grammar does not terminate, the parsing bleeds outside of the listing block.

**Comment by garyrussell** [comment]
Sorry; will do.

**Comment by garyrussell** [comment]
Thanks.

Existing issue https://github.com/atom/language-java/issues/88 there.
