### ISSUE TITLE
Source code block requires a blank line

### ISSUE THREAD

**Issue by antonmoiseev** [asciidoctor/atom-language-asciidoc#20]
Right now the grammar requires at least one blank line after the source code block. This breaks syntax highlighting inside callouts:

![drafts - atom_2015-07-24_13-56-52](https://cloud.githubusercontent.com/assets/182853/8873105/e1b45464-320b-11e5-8f70-98496c1df34a.jpg)

instead of:

![drafts - atom_2015-07-24_13-58-32](https://cloud.githubusercontent.com/assets/182853/8873124/1fc7c5d8-320c-11e5-9223-500cfb573c4e.jpg)

**Comment by nicorikken** [comment]
Confirmed, some initial hacking on the code regexes didn't do it for me. I need a more elaborate understanding on the 'begin' and 'end' matching in the grammar file to solve this issue.
