### ISSUE TITLE
Italic is not properly highlighted

### ISSUE THREAD

**Issue by antonmoiseev** [asciidoctor/atom-language-asciidoc#21]
Underscore inside a word breaks highlighting:
![chapter3_adoc_-__users_amoiseev_code_git_manning_com_agileauthor_fain_drafts_-_atom](https://cloud.githubusercontent.com/assets/182853/8961526/61702cf8-361e-11e5-8086-3ab1da5c47e8.jpg)

**Comment by nicorikken** [comment]
I'm pretty sure I can reuse my fix for the bold highlighting in issue #9. I'll see what I can do.

**Comment by nicorikken** [comment]
Fix implemented, pull-request created.

**Comment by nicorikken** [comment]
This particular issue was fixed in release 1.0.0, even though the italic highlighting in itself can be improved. It can now be too greedy. I'll however close this specific issue.
