### ISSUE TITLE
Single-line comments not recognized?

### ISSUE THREAD

**Issue by stallio** [asciidoctor/atom-language-asciidoc#22]
When I use multi-line comment blocks (lines of /// before and after), Atom correctly recognizes them as comments. But single-line comments are showing up in normal text color:

![screenshot 1041](https://cloud.githubusercontent.com/assets/6136277/9012126/71854282-3780-11e5-909c-e4f6ef98dbfc.png)

I've changed my comment color to blue in this screenshot, but the single-line comment isn't affected.

atom-text-editor::shadow .comment {
  color: blue;
}

**Comment by blablatros** [comment]
I've added a [PR](https://github.com/asciidoctor/atom-language-asciidoc/pull/36) for single-line comments. This is just a quick fix, I am not that familiar with Atom internals, but it should work.

**Comment by nicorikken** [comment]
This issue was addressed in release 1.0.0 Thanks for all the input.
