### ISSUE TITLE
Snippets not showing

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/atom-language-asciidoc#23]
I'm using Atom 1.0.3 and snippets don't show as a drop down menu, not even if waiting or pressing <kbd>ctrl</kbd>+<kbd>space</kbd>.
For instance, I can write `|=` or `--` and then press <kbd>Tab</kbd> to insert the table or code block, but I don't get any insight of available snippets.

Suggestions for other languages like Java or Groovy work correctly.

Btw, also, I tried to run the specs using "Run Package Specs" command but they all fail for the following reaons:
* TypeError: Cannot read property 'grammarForScopeName' of undefined
* TypeError: Cannot read property 'scopeName' of null
* TypeError: Cannot read property 'tokenizeLine' of null

**Comment by woj-tek** [comment]
@abelsromero Have you figured it out? I'm running almost vanilla atom (1.7.0) with latest asciidoc plugins and I'm facing the same problem...

**Comment by abelsromero** [comment]
Nop, I just write what I need "manually"

**Comment by woj-tek** [comment]
Oh shoot. I guess I will have to get used to it also…
Thanks!

**Comment by nicorikken** [comment]
I have noticed this same issue in practice for the table snippets. The tests should however succeed. Maybe you can read into the other packages which DO work to find the fix?

**Comment by mojavelinux** [comment]
Snippets for block now begin with `bl`. So you'd type `bl--` to get a literal block. We don't add code assist with just the delimiter characters alone because it was popping up when people were typing normal sentences.

I've noticed, however, that if you type `bl**` (for a sidebar block), the code assist goes away. Perhaps there are certain characters that we're using which aren't allowed in the shorthand.

**Comment by mojavelinux** [comment]
Of course, now they pop up when you type "b" or "bl". The triggers for code assist in Atom don't seem to be very good, unless I'm missing something.

**Comment by mojavelinux** [comment]
The following thread seems helpful in configuring snippets correctly:

https://discuss.atom.io/t/how-do-you-configure-use-snippets/335/46

It seems we need to focus on the scoping of the snippets better.

**Comment by mojavelinux** [comment]
Aha! I came up with a trick. If you start the prefix with a forward slash (or another non-word character), then Atom won't popup the code assist. However, it will still be watching for the prefix. If you type the whole prefix, then press `<Tab>`, the prefix will expand.

So, if we map the example block to `/==` for instance, then can type:

```
/==<Tab>
```

and it will expand. But the code assist popup never gets in your way.

I propose the following prefixes:

* `///` - comment block
* `/**` - sidebar block
* `/==` - example block
* `/..` - literal block
* `/--` - listing (or source) block
* `/__` - quote block
* `/|=` - table block
* `/++` - pass block

What do you think?

I'm open to other non-word prefix characters other than forward slash, but it feels pretty natural.

**Comment by mojavelinux** [comment]
Using letters in the prefix for a snippet should be avoided until Atom can propose the code assist based on context.

**Comment by nicorikken** [comment]
Seems a smart workaround, worth a try.

**Comment by mojavelinux** [comment]
I also think we should do the same for headings:

* `=1` - level-0 heading
* `=2` - level-1 heading
* ...

The number is the number of equal signs, not the level (in other words, 1 + the level).

**Comment by woj-tek** [comment]
@mojavelinux 

> Snippets for block now begin with bl. So you'd type bl-- to get a literal block. We don't add code assist with just the delimiter characters alone because it was popping up when people were typing normal sentences.

> Aha! I came up with a trick. If you start the prefix with a forward slash (or another non-word character), then Atom won't popup the code assist. However, it will still be watching for the prefix. If you type the whole prefix, then press <Tab>, the prefix will expand.

One tiny thing - this issue (#23) is about snippets not showing up in the code assist - not when typed `--` nor with `bl--` (at any point, not after b, not after bl, not after bl-, etc., not even forced with ctrl+space). Yet they work just fine when completed with `TAB`. So this is different from #11 which basically deals with snippets being overeagerly shown.

For me this issue is a bit weird because I remember it was working just fine, and then it stopped, then after a couple of days it worked for one day and then stopped again completely, which is a bummer because this pop-up with suggestion was really helpful.

**Comment by mojavelinux** [comment]
> For me this issue is a bit weird because I remember it was working just fine, and then it stopped...

This just seems like a bug in Atom. There's nothing in this package that would cause it to work one way or another since it's just a configuration file. When I tested it on a new install of Atom, it works, so I'm convinced it's an upstream issue.

**Comment by mojavelinux** [comment]
> One tiny thing - this issue (#23) is about snippets not showing up in the code assis

I get that, but just don't think they should show. It's super annoying to have them pop up while you're trying to type prose. I'm saying that if we prefix with forward slash, at least for now, we can make it so that they never show intentionally. I think that's the best outcome for #11 and #23.
