### ISSUE TITLE
Support cross-references

### ISSUE THREAD

**Issue by DanielSWolf** [asciidoctor/atom-language-asciidoc#24]
I'm really new to AsciiDoc, so maybe this is just something I got wrong.

According to the [Asciidoctor User Manual](http://asciidoctor.org/docs/user-manual/#xref), a cross-reference works like this:

```
[[shopping]]
.My grocery list
* Apples
* Milk

See <<shopping>>.
```

I'd expect the Atom package to do the following:

* highlight both the anchor and the reference
* allow navigation from the reference to the anchor
* ideally, when I'm typing a reference, offer a list of known anchors.

However, it seems that the package ignores both the anchor and the reference, treating them as regular text:

![screenshot](https://cloud.githubusercontent.com/assets/5963162/9219975/3131749a-40df-11e5-810d-068862a0f8ba.png)

What stumps me is the following screenshot from your README file. The last three lines seem to contain working highlighted references. Only the syntax `{quick-ref}[Quick Reference]` is not one I recognize from the Asciidoctor user manual:

![screenshot](https://camo.githubusercontent.com/51d46fd70e0e524340ecd7cb9b342be94d6dd9b8/68747470733a2f2f7261772e6769746875622e636f6d2f77696b692f6173636969646f63746f722f61746f6d2d6c616e67756167652d6173636969646f632f777269746572732d67756964652d73637265656e73686f742e706e67)

**Comment by abelsromero** [comment]
Currently cross references are not supported, but it's something I'd like to see too. Specially the list of known anchors.

> What stumps me is the following screenshot from your README file. The last three lines seem to contain working highlighted references. Only the syntax {quick-ref}[Quick Reference] is not one I recognize from the Asciidoctor user manual:

That's because they are not a cross reference. These are [attribute references](http://asciidoctor.org/docs/user-manual/#setting-attributes-on-a-document). Basically the picture is a _stripped_ version of this [document](https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/asciidoc-writers-guide.adoc#L20) and omits some parts.
If you check the original document, you'll see that `{quick-ref}` is declared at the beginning and that by writting {...}[...], the document is in fact using the short notation to write URL links ([see](http://asciidoctor.org/docs/user-manual/#url)). In the end when you use a reference {...}, the parser just replaces it with the value of the attribute and then processes it.

**Comment by DanielSWolf** [comment]
I see -- that makes sense. Great work so far, by the way!

**Comment by mojavelinux** [comment]
> * allow navigation from the reference to the anchor
> * ideally, when I'm typing a reference, offer a list of known anchors

I agree these are essential features for a good writing tool. They would be handled by the https://github.com/asciidoctor/atom-asciidoc-preview add-on. This one (atom-language-asciidoc) simply does the syntax highlighting. Perhaps you can spawn this part of the request into a separate issue?

**Comment by abelsromero** [comment]
> * ideally, when I'm typing a reference, offer a list of known anchors

I use both packages (atom-asciidoc-preview and atom-language-asciidoc) and never thought of what should each one do. But this one has me thinking.
I looked into the code and saw that preview is the one handling the auto-completion list of attributes, but I'm not sure this is right. For me (_from my absolute and humble ignorance of atom package patterns_) it makes more sense that things like that should be here. Is there a reason I am missing?

**Comment by mojavelinux** [comment]
@abelsromero I would agree that maybe there should be a third add-on, but I'm not sure we should be bundling user interactivity with a syntax highlighting definition. But if we do decide it belongs here, then yes, the attribute completion needs to be here rather than there. It's a discussion worth having for sure.

**Comment by abelsromero** [comment]
> But if we do decide it belongs here, then yes, the attribute completion needs to be here rather than there. It's a discussion worth having for sure.

I don't a strong opinion on this. If no one has another opinion, we can go ahead and open those issues on https://github.com/asciidoctor/atom-asciidoc-preview. @DanielSWolf wdyt?

**Comment by DanielSWolf** [comment]
I'm new to Atom, so I don't know if there's any convention regarding breakdown into packages. Here are my thoughts, for what they are worth:

* Having one package for syntax highlighting, one for preview, and a third for interaction certainly seems very clean. You can install exactly what you need, and everybody is free to replace any of the three packages with a different similar package.

* Having the preview package do the auto-completion as well makes sense from an engineering standpoint: While syntax highlighting requires only some simple regexes, both preview and auto-completion require a full parse. It would be redundant if two packages did the same parsing independently.

* Going by the package names only, my intuitive guess was that *asciidoc-preview* does only that -- add a preview area -- but doesn't actually do any interaction. Whereas *language-asciidoc* sounds like it does all the rest, like highlighting and auto-completion. Also from a practical standpoint, it is strange to imagine someone wanting both preview and auto-completion, but no syntax highlighting. If there are to be just two packages, this seems the most logical distribution to me.

Tough call. If I had the time, I'd probably go with @mojavelinux' suggestion and do a clean division into three packages. Unfortunately, I'm currently swamped with other projects. So I'll wait for somebody who actually works on these packages to make the call. After that, I'll gladly create a new issue wherever. ;-)

**Comment by mojavelinux** [comment]
Great summary of requirements @DanielSWolf. That seems quite actionable to me. I've always felt that "preview" is too narrow a package name, as you have pointed out. Either we have three packages or we really need to think about having a name which more clearly defines the capabilities. Perhaps:

* language-asciidoc - for the syntax support
* asciidoc-tools (or asciidoc-integration) - for preview, auto-complete, validation etc

The asciidoc-integration could eventually become a meta-plugin for even more fine-grained packages. Based on how the Atom ecosystem is organized, I think it's important to always keep the syntax as a separate package.

**Comment by nicorikken** [comment]
To add to the package separation discussion: I can see a linter come into being, which can be based on the asciidoctor.rb commandline tool. This would also require a more extensive level of document parsing.

**Comment by mojavelinux** [comment]
:+1: 

A linter is sure to become a key tool in the writer's toolbox.

**Comment by nicorikken** [comment]
HI recognize the need for cross-reference highlighting from my recent editing needs. Doesn't seem to be so major in its essence. Something like: `<<document-b.adoc#section-b,Section B>>` should be supported [[ref]](http://asciidoctor.org/docs/user-manual/#inter-document-cross-references). The syntax could be derived from the `link:...` highlighting. Maybe it is worth explicitly distinguishing the section (after the `#`) in highlighting, as this is used often during cross-referencing.
If I find time I'll probably pick this one up, although this would be a great beginner-bug as well.

**Comment by mojavelinux** [comment]
Basic cross reference highlighting is currently supported.

![xref-simple](https://cloud.githubusercontent.com/assets/79351/16639508/80f82e34-43ad-11e6-9d4b-666bec3206c3.png)

However, there's no special highlighting for an inter-document cross reference.

![interdoc-xref](https://cloud.githubusercontent.com/assets/79351/16639557/ca74c752-43ad-11e6-9909-95c19b483499.png)

(note that the .adoc extension is optional in an interdocument xref)

**Comment by ldez** [comment]
Reported to https://github.com/asciidoctor/atom-asciidoc-assistant/issues/12

**Comment by nicorikken** [comment]
@ldez I'd like to opt for better highlighting, which seems to have been the initial motivation for this issue. I assume you closed it for the completion and linting duscussion? If so I'd like to keep this one open or make a duplicate.
