### ISSUE TITLE
Asciidoctor syntax highlighting on lists

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/atom-language-asciidoc#26]
I can see in the code that lists are supported (https://github.com/asciidoctor/atom-language-asciidoc/blob/master/grammars/asciidoc.cson#L141) but the default color is too subtle:

![syntax-highlighting](https://cloud.githubusercontent.com/assets/333276/9561764/a4ed7ce0-4e53-11e5-8890-ee69fa0ccdcd.png)

Also numbered lists are currently not supported ?

**Comment by ldez** [comment]
I have create a PR for bullet color : #30

**Comment by ldez** [comment]
This issue can be close, version 1.0.0 fix the problem.

**Comment by Mogztter** [comment]
![great](https://cloud.githubusercontent.com/assets/333276/14936108/27c69408-0ee8-11e6-8126-bc770330652e.png)
:+1:
