### ISSUE TITLE
Markdown compatibility syntax highlighting

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/atom-language-asciidoc#27]
Asciidoctor have markdown compatibility. It would be nice to have syntax highlighting for title, block quotes and horizontal rules. See http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#markdown-compatibility

**Comment by nicorikken** [comment]
The scope of this seems reasonable, as it is only a subset of the Markdown spec. Does this only concern Asciidoctor or generic Asciidoc as well?

**Comment by mojavelinux** [comment]
Asciidoctor is AsciiDoc. I do believe that some compatibility with Markdown belongs in the AsciiDoc specification. In fact, it would be more correct to say that popular syntax from Markdown has been adopted by AsciiDoc in order to easy interoperability / migration.

I'm most interested in the following features:

* Markdown-style headings
* Markdown-style fenced code blocks
* Markdown-style block quotes
* Markdown-style horizontal rules

**Comment by nicorikken** [comment]
I wasn't able to find information on the markdown compatibility in the [asciidoc user guide](http://asciidoc.org/userguide.html). But either way, Asciidoctor supports it. The headings are already prepared in the pull request #29

**Comment by Mogztter** [comment]
Great :+1:

**Comment by mojavelinux** [comment]
> I wasn't able to find information on the markdown compatibility in the asciidoc user guide.

You should be looking at the Asciidoctor User Manual. The AsciiDoc Python user guide is for the deprecated Python implementation and is only relevant for people still using that legacy implementation. Asciidoctor is AsciiDoc.

For a quick reference, see http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#markdown-compatibility

**Comment by nicorikken** [comment]
@mojavelinux I probably missed out on the Asciidoc/Asciidoctor primer then. I assumed: Asciidoc = language definition + reference implementation, Asciidoctor = fancy set of Asciidoc supporting tools. Thanks for clearing that up.

The pull request #29 for Markdown-style headers has just been merged, and you should see it pop up in your editor soon.

1 down, 3 to go.

**Comment by mojavelinux** [comment]
We need to do a better job of getting that message across, so you didn't miss anything.

I oversimplified the statement about Asciidoctor and AsciiDoc. AsciiDoc is indeed the language. Asciidoctor is a processor (aka implementation) and toolchain for that language (AsciiDoc Python is another). Right now, Asciidoctor is also taking care of the AsciiDoc language, improving it by making it more modern, consistent and concise. (AsciiDoc Python gave up these reins). Eventually, we want to form a clear and possibly independent definition of AsciiDoc (code named UniDoc), but I don't think we're quite ready for that yet.

**Comment by nicorikken** [comment]
The corresponding PR #76 contributed by @ldez has just been merged into master, and will become available in the upcoming release.

**Comment by ldez** [comment]
The version 1.1.0 fix this issue, it can be closed.

**Comment by mojavelinux** [comment]
Did you mean v1.2.0? Or was it included in the v1.1.0 release? Let's set the milestone correctly, then close it.

**Comment by ldez** [comment]
Sorry mistake :smile: 
It's included in the next release (>1.1.0).

**Comment by mojavelinux** [comment]
Great, then the milestone is right. I'll close the issue.
