### ISSUE TITLE
Asciidoctor syntax highlighting on links

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/atom-language-asciidoc#28]
It would be nice to have syntax highlighting on links (similar to the markdown package).
Here is an example with the Markdown syntax highlighting:

![syntax-high-md-links](https://cloud.githubusercontent.com/assets/333276/9561777/5013c714-4e54-11e5-84fc-e34730034d0c.png)

**Comment by nicorikken** [comment]
This works since PR #74 therefore I close this issue.
<img width="263" alt="screen shot 2016-05-07 at 20 12 49" src="https://cloud.githubusercontent.com/assets/7458098/15093713/19ea218a-1490-11e6-87b6-47919ac9b2a0.png">

**Comment by Mogztter** [comment]
Great thanks 😉
