### ISSUE TITLE
Add tables support

### ISSUE THREAD

**Issue by antonmoiseev** [asciidoctor/atom-language-asciidoc#3]
Initial support I actually just added, but wanted to associate an issue with the commit to attach a screenshot with current highlighting features:
![table](https://cloud.githubusercontent.com/assets/182853/3007684/f32de50c-de97-11e3-8ee7-897dfe1dcced.png)

**Comment by nicorikken** [comment]
It seems the table support is present in the grammar, but the styles aren't properly used. it seems some color needs to be assigned to `.table.support`. I tried equating it with `.markup.macro.inline` and `.markup.macro.block`. @ldez Any LESS styling ideas?

**Comment by ldez** [comment]
I'm going to think about the topic.

**Comment by mojavelinux** [comment]
This is also a great opportunity to try to play around with scopes. An AsciiDoc table cell should recognize other blocks, but all other table cells should not allow blocks. This seems to be something the grammar can handle.

**Comment by ldez** [comment]
Fix by  #104
