### ISSUE TITLE
Invalid link highlight

### ISSUE THREAD

**Issue by ldez** [asciidoctor/atom-language-asciidoc#31]
Invalid link highlight:

```
foo foo http://fuu.bur[FuuBur]
foo foo https://fuu.bur[FuuBur]
```
![capture](https://cloud.githubusercontent.com/assets/5674651/9592438/3570ed4c-5043-11e5-9c9d-cf9596af2782.PNG)

Relates #17

**Comment by flyisland** [comment]
+1, same issue!
