### ISSUE TITLE
Invalid inline image highlight

### ISSUE THREAD

**Issue by ricardocvasconcelos** [asciidoctor/atom-language-asciidoc#33]
The highlight is not set properly when including an inline image.

![image](https://cloud.githubusercontent.com/assets/7273835/10041200/55bfd916-61da-11e5-88a4-09a348e57497.png)

**Comment by nicorikken** [comment]
This seems to work just fine in the current version of the package (master at least). Or I'm missing the actual problem in this case.

**Comment by mojavelinux** [comment]
This is now being caught by the generic inline macro fix that @ProgramFan added. We'll probably want to split that out eventually into more specific matchers, but for now I think it does a sufficient job.

**Comment by mojavelinux** [comment]
So yes, this now works better than it did before. We should probably close and reopen a more specific issue when it comes time.

**Comment by ricardocvasconcelos** [comment]
I've tested this behaviour with version 0.12.0 (Atom 1.7.2, Win8.1). If someone has changed that I agree that you should close the issue.
I will test that again in the new release and give proper feedback, if necessary.

**Comment by mojavelinux** [comment]
The repository has advanced well beyond 0.12.0. You can test it by cloning the repository into ~/.atom/packages or using the atom link feature. We should definitely explain how this is done in the new contributing guide so it's easier for people to test it.

**Comment by nicorikken** [comment]
This issue is still addressed in the new release 1.0.0, please give it a try:
<img width="544" alt="screen shot 2016-04-29 at 08 37 34 1" src="https://cloud.githubusercontent.com/assets/7458098/14909588/b757ea12-0de5-11e6-8303-a157452bd773.png">

**Comment by ricardocvasconcelos** [comment]
It works fine in the new version. Great work with this release!

**Comment by nicorikken** [comment]
Nice, I'll close this issue then.
