### ISSUE TITLE
Single apostrophe breaks highlighting

### ISSUE THREAD

**Issue by lucascosti** [asciidoctor/atom-language-asciidoc#34]
If a single apostrophe is used in the text, it breaks the colored highlighting for all following text.

e.g. below, the word `don't` makes all the subsequent text green. 

![screenshot from 2015-10-12 14-05-59](https://cloud.githubusercontent.com/assets/4434330/10421402/5a6427b8-70eb-11e5-8afc-473d296a8725.png)

**Comment by nicorikken** [comment]
This issue doesn't seem to be an issue on the current version of the package. This issue can therefore be closed.

**Comment by mojavelinux** [comment]
I can confirm that this problem appears to have been resolved.

**Comment by lucascosti** [comment]
Yep, confirmed this issue isn't occurring anymore. There wasn't an asciidoc language update, so was it an Atom bug? \*shrugs shoulders*.
