### ISSUE TITLE
Wrong color of elements inside comment blocks

### ISSUE THREAD

**Issue by blablatros** [asciidoctor/atom-language-asciidoc#35]
Notice how the heading is correctly faded, whereas bold text and include directive remain unaffected.

![comment](https://cloud.githubusercontent.com/assets/4815474/10576930/7a568aee-7667-11e5-9de9-468c14efe9ea.png)

**Comment by nicorikken** [comment]
Seems to be a styling issue, as cursor scope is logged properly. Thanks for reporting.

**Comment by nicorikken** [comment]
This issue got fixed with the 1.0.0 release.
