### ISSUE TITLE
Inline code blocks not highlighted inside parentheses

### ISSUE THREAD

**Issue by anmonteiro** [asciidoctor/atom-language-asciidoc#38]
example:

```asciidoc
// this one gets highlighted
`inline code`

// this one does not
(`inline code`)
```
I'd say the regex [here](https://github.com/asciidoctor/atom-language-asciidoc/blob/3abc02ee7848c1229846cbeabd6583a7bb928abd/grammars/asciidoc.cson#L373) should probably be converted from:
```
(?<=^|\\s)`[^`]+`
```
to:
```
(?<=^|\\W)`[^`]+`
```

Please say if you'd like me to open a pull request with the changes

**Comment by mojavelinux** [comment]
All the inline regexps should try to match what core does as close as possible.

In this case, see https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L1188

**Comment by nicorikken** [comment]
@mojavelinux The referenced file has changed underneath you. Pro-tip: reference a specific commit, rather than a branch head. Can I conclude that this needs to be improved, taking the related asciidoctor.rb regex as input?

**Comment by mojavelinux** [comment]
> Pro-tip: reference a specific commit

:+1: 

See (updated): https://github.com/asciidoctor/asciidoctor/blob/v1.5.4/lib/asciidoctor.rb#L1177-L1178

> Can I conclude that this needs to be improved, taking the related asciidoctor.rb regex as input?

I think we need to follow the work you've done on bold and italic to include monospaced.

I understand that "raw" is a shorthand for "monospaced" in the atom/textmate grammar definition, so I'm okay with keeping that as long as we explain it in the comments.
