### ISSUE TITLE
dashes in code block closes it prematurely

### ISSUE THREAD

**Issue by ssfrr** [asciidoctor/atom-language-asciidoc#39]
When `----` appears in the code block (even when it's not the first non-whitespace character), the syntax highlighter seems to think the code block is over, but in the rendered document it seems to show up fine. See the following image to see what's going on. The table should be part of the code block, which ends at the following `----`. This is rendering as if the closing `----` is starting a new code block.

![image](https://cloud.githubusercontent.com/assets/734386/11797736/31ea678c-a293-11e5-9438-6cf28d45736d.png)

**Comment by mojavelinux** [comment]
The regexp for the end of the block should be looking for hyphens at the start of a line, not anywhere in the line as it seems to be doing.

I also noticed the following pattern for looking for the start of the listing block:

```
'(^\\s*-{4,}\\s*$)'
```

It shouldn't be allowing space at the beginning of the line. All those regexps needed to be adjusted to remove the first `\\s*`.

**Comment by mojavelinux** [comment]
Btw, I don't understand how it is matching the end of the block, so I cannot comment on what is wrong.

**Comment by ssfrr** [comment]
not sure if it's relevant, but this code block has a type `jlcon`, which isn't one of the code types that language-asciidoc has built-in support for.

**Comment by mojavelinux** [comment]
If you change it, does it change where it cuts off (just pick another language that resembles jlcon roughly).

**Comment by ssfrr** [comment]
No, looks like it doesn't (sorry for the red herring). It still starts rendering the following paragraph as code, as if it started a new code block.

![image](https://cloud.githubusercontent.com/assets/734386/11799098/15adf276-a29f-11e5-936e-3711bd1bb7fd.png)
