### ISSUE TITLE
Awesome UX for "backend" attribute should be extended for other attributes

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/atom-language-asciidoc#44]
![screen shot 2016-03-21 at 3 40 46 pm](https://cloud.githubusercontent.com/assets/952793/13911416/c272ffa0-ef7b-11e5-9026-b524f4a400f4.png)

See how the Backend attribute has microcopy help provided. 
I came across this by accident when mistyping something that the plug-in recognised.

How many other known attributes have this contextual help? 
If it's not many, we should totally extend this as much as we can. It is a great UX and reminder of what attributes do. 

What are the constraints of this microcopy? Char limits?

**Comment by mojavelinux** [comment]
Now that we have identified all the attributes, we have the foundation to provide these descriptions. This may even lead us to storing them in a format that can be easily consume, which we can then use to create the attribute tables in the user manual. Now that would be *sweet*.

http://asciidoctor.org/docs/user-manual/#attribute-catalog

**Comment by anthonny** [comment]
Completion is provided by the preview plugin:

https://github.com/asciidoctor/atom-asciidoc-preview/blob/master/completions.json

**Comment by nicorikken** [comment]
Indeed this completion is provided by *asciidoc-preview* rather then this *language-asciidoc* package. Having completion included in a source-code oriented package would make a lot of sense. The current implementation seems to be based on an old API version, according to [the autocomplete-plus wiki](https://github.com/atom/autocomplete-plus/wiki/Autocomplete-Providers), so maybe this feature can be expanded and updated.

**Comment by anthonny** [comment]
Fixed with this https://github.com/asciidoctor/atom-asciidoc-preview/issues/54 i suppose that the wiki is not up-to-date, or maybe the API has changed again

**Comment by mojavelinux** [comment]
Thanks @anthonny!

We definitely need to figure out the right way to divide up the behaviors between plugins. One way to look at it is that the language plugin deals with the editor pane and the preview plugin deals with the preview pane. If putting autocomplete in the language plugin is too much, then I think we need a third plugin, atom-asciidoc-assist. I don't think autocomplete should be in the preview plugin in the future.

**Comment by ldez** [comment]
Since 1.0.0 of [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview), the autocompletions have been migrated to a new package: [autocomplete-asciidoc](https://atom.io/packages/autocomplete-asciidoc)
