### ISSUE TITLE
Spell-checking in Asciidoc documents

### ISSUE THREAD

**Issue by ondrejsv** [asciidoctor/atom-language-asciidoc#5]
Is it possible to spell-check the Asciidoc documents in Atom? Of course, without marking Asciidoc keywords and other markup as misspelled words.
(Atom uses it's own spellcheck module. I was briefly looking at its code and I don't think it can handle spell-checking of anything else than plain text right now.)

**Comment by DMLou** [comment]
Atom's spell checker seems to work just fine for Markdown, which is at least superficially similar to Asciidoc. I don't know why it wouldn't also be adaptable for Asciidoc.

**Comment by DMLou** [comment]
I figured out how to enable spell-checking for Asciidoc in Atom. You need to go into the spell-check package's settings and add "source.asciidoc" to the "Grammars" setting. Jot down the default values as well as I think if you just type "source.asciidoc" into the text box, it'll delete those other grammar settings. For example, my Grammars setting right now is: source.gfm, text.git-commit, text.plain, text.plain.null-grammar, source.asciidoc

**Comment by antonmoiseev** [comment]
@DMLou right, spell-checking should be manually enabled for Asciidoc, discussed it [here](https://discuss.atom.io/t/how-to-enable-spell-checking-for-another-language/4895/7?u=amoiseev).

Investigated another point that Dan and @ondrejsv were discussing - ignoring Asiciidoc-specific syntax elements. There is a good issue to track - atom/spell-check#2. Our grammar definition file is already aware about the structure, so if we could just mark prose with special CSS class that would be recognized by spell-checker, it think it would be the easiest solution.

**Comment by DMLou** [comment]
@antonmoiseev Interesting... as I didn't see any complaints from the spell checker concerning AsciiDoc-specific syntax, but then again, I'm not an advanced Asciidoc user (I mostly use it for my own personal notes files as well as generating man pages). Someone who pushes its features more *may* have more difficulty than I did, I guess.

**Comment by nicorikken** [comment]
The spell check is nowadays working by default. Has anyone encountered any keyword spellcheck errors or alike which require further work? Otherwise I believe this issue can be closed.

**Comment by mojavelinux** [comment]
According to the Spell Check Package:

> By default spell check is enabled for the following files:
>
> * Plain Text
> * GitHub Markdown
> * Git Commit Message
> * AsciiDoc

This is likely driven by the fact that the Atom documentation team uses AsciiDoc for the Atom documentation :)

When I enable spell check, I notice that it tries to spellcheck things like attribute entries. I think the way this is controlled is through the use of the "name" and "contentName" fields. We should have a key for "content.asciidoc"  so we can configure the spell check to only check items which are considered content (and not general markup). Let's file a separate issue for that reclassification.

**Comment by mojavelinux** [comment]
The reason spellcheck is getting applied to everything is because the scopeName on the root is "source.asciidoc" which is what spell check is wired to.

**Comment by mojavelinux** [comment]
@nicorikken When you close this issue, could you open another issue titled "Only apply spell check to content" (which means we have to label the scopes more accurately).

**Comment by mojavelinux** [comment]
It looks like we've decided to keep this issue open and close #63 instead. Either way, I think the goal is clear.

**Comment by mojavelinux** [comment]
When you enable the spell check package for AsciiDoc files, it always starts on by default. If you want to start off by default and toggle it on with an Atom command / keyboard shortcut, see the tip in the following issue: https://github.com/atom/spell-check/issues/137

**Comment by ldez** [comment]
Mistake... I revert

**Comment by mojavelinux** [comment]
I think it's fine since the two issues are linked. We only need one of them open.

**Comment by ldez** [comment]
:sob:
