### ISSUE TITLE
Document how to run tests

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/atom-language-asciidoc#50]
Document how to run tests in a file named HACKING.adoc or CONTRIBUTING-CODE.adoc.

I think it's as simple as:

```
atom --test spec
```

On OSX and Debian systems, you can use the build-package.sh script.

```
curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh > build-package.sh
sh build-package.sh
```

**Comment by nicorikken** [comment]
Similarly, you can run `Window: Run Package Specs` using the Command Pallet when working in the package using atom. `atom --test spec` seems to work on OS X as well.

**Comment by mojavelinux** [comment]
We should definitely document both approaches as they are both important in different circumstances.

**Comment by nicorikken** [comment]
Just added this content to PR #54 Maybe some options can be left out though.

**Comment by mojavelinux** [comment]
:+1:

**Comment by ldez** [comment]
This issue can be close.
