### ISSUE TITLE
Update terminology used in grammar file

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/atom-language-asciidoc#53]
There are a lot of places in the grammar file where the terminology used doesn't match the terminology as defined by AsciiDoc. Update the terminology in the grammar file so it's consistent with the language definition.

For example, AsciiDoc prefers:

* "strong" instead of "bold"
* "emphasis" instead of "italic"
* "attribute reference" instead of "substitution"
* "xref" instead of "reference"
* "monospaced" instead of "raw"
* "char(acter) reference" (or "entity") instead of "htmlentity"
* "url" instead of "link" (and certainly not "underline")

Additionally, we shouldn't be matching explicit paragraph block style names on top of paragraphs as those names are extensible.

**Comment by nicorikken** [comment]
Although I agree with this proposed change regarding the naming of partial grammar, and custom style elements, if I'm not mistaken (did a small test to check), deviating from the commonly used descriptors like bold, italic, can break current theme compatibility. That seems less desirable to me, as it might take a while for themes to catch up. What do you think?

**Comment by mojavelinux** [comment]
I'm okay with using the common terminology in the names. Where I'd like to see the update is in the comments and in the file names. In other words, we should describe what we are matching using the AsciiDoc syntax, but use the closest terminology known to themes for the assigned names.

For example, "Matches bold unconstrained phrases" should be "Matches strong unconstrained phrases".

We could also consider adding both the AsciiDoc terminology in the name and the closest match to the terminology in the themes. For example: "markup.bold.strong.unconstrained.asciidoc".

(Btw, I don't see much value in using "constrained" and "unconstrained" in the name value. I don't see any case where these would be highlighted differently).

**Comment by ldez** [comment]
"constrained" and "unconstrained" in the name value is very useful to debug. :wink:

**Comment by mojavelinux** [comment]
Hmm, I see.

**Comment by nicorikken** [comment]
@ldez I removed the 'constrained' 'unconstrained' distinction in the PR #94 For debugging it is pretty simple to disable either of the two, or to rename them. So although I see the debugging use-case, I opt for simplicity. What do you think?

**Comment by mojavelinux** [comment]
We have an inconsistency in how we refer to formatted text (which I agree, is true in core as well).

* strong
* emphasis
* monospaced

I think it should either be:

* strong
* emphasized
* monospaced

or

* strong
* emphasis
* monospace

I prefer the second. So we should drop the "d" in "monospaced".

**Comment by ldez** [comment]
All the required changes are done now.

**Comment by mojavelinux** [comment]
:+1:
