### ISSUE TITLE
Syntax highlighting breaks in Atom 0.174

### ISSUE THREAD

**Issue by DMLou** [asciidoctor/atom-language-asciidoc#6]
This might be related to some of the selectors being deprecated. Anyway, most of the syntax highlighting is non-existent once I upgraded to Atom 0.174 (it may have vanished earlier as well, but I only noticed with this release of Atom).

Atom's Deprecation Cop brings up the following issues:

* Use the `atom-text-editor` tag instead of the `editor` class.
* Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension. If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by mojavelinux** [comment]
Thanks for reporting! @DMLou or @antonmoiseev, will you have time to take a look at this? If not, perhaps we can solicit for help from the community.

**Comment by DMLou** [comment]
I can try to take a look, but I think it would be better if @antonmoiseev and/or others in the community looked as well. I'm mostly a C/C++ programmer with a bit of Python, not a JavaScript guy, so it'll probably take me a bit longer than some others to figure this one out.

**Comment by mojavelinux** [comment]
Thanks @antonmoiseev!

**Comment by DMLou** [comment]
Thanks a bunch, @antonmoiseev !

**Comment by nancym** [comment]
I just did a clean install of Atom 0.175.0 and language-asciidoc 0.11.0 and Deprecation Cop says:

stylesheets\asciidoc.atom-text-editor.less
   Use the `atom-text-editor` tag instead of the `editor` class.

For me, at least, this is still an issue.

**Comment by antonmoiseev** [comment]
@nancym agree. Fixed all deprecation cop's warnings
