### ISSUE TITLE
Highlighting of inline macros extends to the start of the line

### ISSUE THREAD

**Issue by ygra** [asciidoctor/atom-language-asciidoc#66]
When writing something like this:

    Some text, followed by image:foo.png[]

everything before the colon is highlighted as if it all were the macro name.

**Comment by mojavelinux** [comment]
Thanks for pointing this out. The macro name should be word characters
only, no spaces.

**Comment by nicorikken** [comment]
Resolved in current master
<img width="310" alt="screen shot 2016-05-02 at 22 24 22" src="https://cloud.githubusercontent.com/assets/7458098/14966825/a99a2666-10b4-11e6-8fcd-b584e2740bad.png">
