### ISSUE TITLE
Regression related to bold syntax.

### ISSUE THREAD

**Issue by ldez** [asciidoctor/atom-language-asciidoc#71]
![capture du 2016-04-29 12-03-17](https://cloud.githubusercontent.com/assets/5674651/14913324/8323e224-0e02-11e6-8417-c15d574d6329.png)

see [spec/fixtures/asciidoctor-lang.adoc](https://github.com/asciidoctor/atom-language-asciidoc/blob/master/spec/fixtures/asciidoctor-lang.adoc)

**Comment by ldez** [comment]
the regression is more important:

![capture du 2016-04-30 00-42-33](https://cloud.githubusercontent.com/assets/5674651/14931533/8adecc3a-0e6c-11e6-9ef2-43ec41f42e44.png)

**Comment by ldez** [comment]
I think multi-lines in this case must be dropped at least temporarily.

**Comment by nicorikken** [comment]
Technically this should be correct still. Although code-block matching should probably be ordered to be matched before matching the bold content.

**Comment by ldez** [comment]
It's not a problem with block, see my 2nd comment.

**Comment by nicorikken** [comment]
I'll have to look into the details of the issue, whether we can get this to work properly. Maybe dropping multi-line support isn't so bad, but those previous regex's have flaws as well.

**Comment by nicorikken** [comment]
Granted, ordering is not the issue in multi-line. This seems buggy, not suitable for a fix using regex exclusion.

**Comment by mojavelinux** [comment]
It is too bad that we can't support multi-line matches yet. But I agree that we shouldn't try to force it because it has major side effects. C'est la vie.

Can we set the milestone in which this was fixed?
