### ISSUE TITLE
Release 1.1.0 !!!

### ISSUE THREAD

**Issue by ldez** [asciidoctor/atom-language-asciidoc#77]
:mega:  :gift: Just because I'm happy :fireworks:  :tada:

**Comment by nicorikken** [comment]
Same here 🎉 Nice to see this level of progress in this amount of time. Not this package is finally at an acceptable base level of quality and features. 👍

**Comment by mojavelinux** [comment]
Awesome! @ldez & @nicorikken, you've made many people very happy too. A hero :trophy: to both of you!
