### ISSUE TITLE
Use the `atom-text-editor` tag instead of the `editor` class.

### ISSUE THREAD

**Issue by mcmarto** [asciidoctor/atom-language-asciidoc#8]
In stylesheets\asciidoc.less: Use the `atom-text-editor` tag instead of the `editor` class.

Reported by Atom's own deprecation-cop plugin

**Comment by antonmoiseev** [comment]
You probably use an outdated version of the plugin, this issue [has been fixed](https://github.com/asciidoctor/atom-language-asciidoc/commit/c59dacb97ff92c29a5dc02e91824bd39bb76265d#diff-0060c14a8f784bab7b37ad30c57dcb9bR5) in `v0.11.1`.

**Comment by mcmarto** [comment]
Yes, I spotted this shortly afterwards. Sorry for the unintended support noise !
