### ISSUE TITLE
List with bold is not correctly highlighted

### ISSUE THREAD

**Issue by alefragnani** [asciidoctor/atom-language-asciidoc#9]
Hi,

When I use a list with bold at the beginning, the bold is not correctly highlighted. Look at the code below:

![print-asciidoc-list-bold](https://cloud.githubusercontent.com/assets/3781424/7171837/40e6c3be-e3b4-11e4-9d42-757e7a8d5a1f.png)

The asciidoc-preview package otherwise, shows correctly.

Thanks

**Comment by antonmoiseev** [comment]
I see, thank you for reporting this! We'll take a look.

**Comment by nicorikken** [comment]
This requires a change in this part of the language definition: https://github.com/asciidoctor/atom-language-asciidoc/blob/master/grammars/asciidoc.cson#L277-L309

**Comment by nicorikken** [comment]
I started working on this issue, learning Ruby regex's on the job. It seems I basically have to exclude the bullet matches, both before and after the bold section. If somebody is eager to help, you can start hacking around at http://rubular.com/ for starters.

**Comment by nicorikken** [comment]
The regex `(?:^|\s|(?:^\s*[\*]{1,5}[\s]))(\*[^\s^\*]+[^\*]*\*)(?:\s|$)` seems to be working fine, although non-capture groups are clearly not the right solution. This will have to be transformed to lookahead and lookbehind statements, although in particular the lookbehind is difficult as not all regex-features are allowed.

**Comment by mojavelinux** [comment]
>  learning Ruby regex's on the job

:+1:  That's how we roll around here ;)

**Comment by nicorikken** [comment]
@mojavelinux Does there happen to be a repository of asciidoc(tor) related regex's?

**Comment by mojavelinux** [comment]
You can find most of them in constants in the following file:

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L398-L1099

**Comment by nicorikken** [comment]
Nailed it! I'll add some of my in-progress-tests and make a pull request. Also got some additional grammar improvements underway as well. `(?<=^|\\s)(\\*[^\\s^\\*][^\\*]*\\*)(?=\\s|$)`

**Comment by mojavelinux** [comment]
Great job!

**Comment by nicorikken** [comment]
I do have one additional test, which does work in the editor, but fails via the spec file. A bit of an edge-case though:

**Comment by mojavelinux** [comment]
I'm not quite sure I understand this test. Is this the sample text?

```
* *Not bold
text*
```

If so, that should match as bold text (so the statement the text is making is incorrect).

**Comment by nicorikken** [comment]
Indeed, the text is misleading. Although the tests succeed, the highlighting fails in my editor. I'll have to solve some other problems with this issue already, so I'll have to correct the tests as well.

**Comment by mojavelinux** [comment]
:+1:

**Comment by nicorikken** [comment]
**wrongly posed in issue** #46

Based on the asciidoctor.rb source, and taking in my learnings in the italic highligh ( #21 ), I've now come up with two matches, for both constrained and unconstrained phrases:

Constrained: `'match': '(^|[^\\w;:}])(?:\\[([^\\]]+?)\\])?(?!\\*{3})(\\*\\S\\*|\\*\\S[\\s\\S]*?\\S\\*)(?![\\w])'`
Unconstrained: `'match': '\\\\?(?:\\[([^\\]]+?)\\])?(\\*\\*[\\s\\S]+?\\*\\*)'`

It needs some more testing and unit tests, but for now this seems to be the right solution.

**Comment by mojavelinux** [comment]
Since you are now catching the attribute list in front of the formatting (e.g., `[.role]*text*`), I think we should assign different names to the captures so that they can be styled independently.

For the example I gave, I'm thinking of something like:

```
'captures':
  '1': 'name': 'markup.attrlist.asciidoc'
  '2': 'name': 'markup.bold.asciidoc'
```

In order for this to work, you need to adjust the pattern so that it captures the right segments. As you probably know, a capture is done using `(...)`. You can create a non-capturing group using `(?:...)`. So we need to move around the use of `?:` so that it captures the attribute list and the formatting.

For the constrained case, that might look like:

`'match': '(?:^|[^\\w;:}])(\\[(?:[^\\]]+?)\\])?(?!\\*{3})(\\*\\S\\*|\\*\\S[\\s\\S]*?\\S\\*)(?![\\w])'`

Notice we don't capture the leading character and we capture the whole attribute list instead of the just the contents. This is different from what the processor does because the processor is interested in the content of these matches, not in styling them.

**Comment by mojavelinux** [comment]
For the example I gave, this will give the following output:

```
<span class="source asciidoc"><span class="markup attrlist asciidoc">[.role]</span><span class="markup bold asciidoc">*text*</span></span>
```

**Comment by mojavelinux** [comment]
We may want to put a span around the whole match too:

```
'captures':
  '1': 'name': 'markup.bold.asciidoc'
  '2': 'name': 'markup.attrlist.asciidoc'
  '3': 'name': 'markup.text.asciidoc'
```

**Comment by nicorikken** [comment]
This issue got practically fixed in version 1.0.0, although the last comments of @mojavelinux can still be taken as possible enhancements.

**Comment by nicorikken** [comment]
@mojavelinux I did some experimentation with the attributelist. Would you like to match the whole list or the inner values? (or both, could be as well). And what naming scheme would be appropriate?

**Comment by mojavelinux** [comment]
I think we can start just by highlighting the attribute list as a whole (including the brackets). We can use something like `markup.meta.attrlist.asciidoc`.

**Comment by mojavelinux** [comment]
An attribute list is a lot like an annotation in a language like Java. Since it's meta information, it should be dimmer than the normal text (i.e., more transparent, like gray). This makes it easier to read the text in the sentence.

**Comment by nicorikken** [comment]
The attribute list is now matched, and the style has been made more uniform, with the PR #111 being the latest in the long list of improvements. Apart from improving the naming, the grammar styling itself is now stable and resolved, so I'll close this issue.
